version: '2.1'
networks:
  my-network:
    driver: bridge
services:
  db:
    image: mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    networks:
      - "my-network"

  be:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "npx prisma generate && npx prisma db push && node src/index.js"
    ports:
      - "3000:3000"
    networks:
      - "my-network"
    depends_on:
      db:
        condition: service_started
    links:
     - db